// quotes.js - Localized Literary Backup for Toma
window.englishQuotes = [
    "I love you not only for what you are, but for what I am when I am with you. -Roy Croft",
    "In vain have I struggled. It will not do. My feelings will not be repressed. You must allow me to tell you how ardently I admire and love you -Jane Austen",
    "Whatever our souls are made of, his and mine are the same. -Emily Bronte",
    "I would rather share one lifetime with you than face all the ages of this world alone. -J.R.R. Tolkien",
    "You are my heart, my life, my one and only thought. -Arthur Conan Doyle",
    "I am who I am because of you. You are every reason, every hope, and every dream I've ever had. -Nicholas Sparks",
    "I love you without knowing how, or when, or from where. -Pablo Neruda",
    "You pierce my soul. I am half agony, half hope. -Jane Austen",
    "I wish I knew how to quit you. -Annie Proulx",
    "I love you more than there are stars in the sky and fish in the sea. - Nicholas Sparks",
    "I am yours, don't give myself back to me. -Rumi",
    "Doubt thou the stars are fire, doubt that the sun doth move, doubt truth to be a liar, but never doubt I love. -William Shakespeare",
    "I love you, and I will love you until I die, and if there's a life after that, I'll love you then. -Cassandra Clare",
    "You are my best friend as well as my lover, and I do not know which side of you I enjoy the most. -Nicholas Sparks",
    "I fell in love the way you fall asleep: slowly, and then all at once. -John Green",
    "To love or have loved, that is enough. Ask nothing further. -Victor Hugo",
    "I would always rather be happy than dignified. -Charlotte Bronte",
    "Love is or it ain't. Thin love ain't love at all. -Toni Morrison",
    "I love you as certain dark things are to be loved, in secret, between the shadow and the soul. -Pablo Neruda",
    "I carry your heart with me. -E.E. Cummings",
    "If I had a flower for every time I thought of you, I could walk through my garden forever. -Alfred Lord Tennyson",
    "I love thee to the depth and breadth and height my soul can reach. - Elizabeth Barrett Browning",
    "Love looks not with the eyes, but with the mind, and therefore is winged Cupid painted blind. -William Shakespeare",
    "I love you, and that's the beginning and end of everything. -F. Scott Fitzgerald",
    "The best love is the kind that awakens the soul and makes us reach for more. -Nicholas Sparks",
    "I love you not because of who you are, but because of who I am when I am with you. -Gabriel Garcca Marquez",
    "You should be kissed and often, and by someone who knows how. -Margaret Mitchell",
    "I seem to have loved you in numberless forms, numberless times, in life after life, in age after age forever. -Rabindranath Tagore",
    "To be your friend was all I ever wanted; to be your lover was all I ever dreamed. -Valerie Lombardo",
    "I love you begins by I, but it ends up by you. - Charles de Leusse",
    "Come live in my heart, and pay no rent. -Samuel Lover",
    "Grow old along with me; the best is yet to be. -Robert Browning",
    "When I saw you I fell in love, and you smiled because you knew. -Arrigo Boito",
    "I love you more than I have ever found a way to say to you. -Ben Folds",
    "My bounty is as boundless as the sea, my love as deep; the more I give to thee, the more I have, for both are infinite. -William Shakespeare",
    "I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more. -Angelita Lim",
    "If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you. -A.A. Milne",
    "I would find you in any lifetime. -Kamand Kojouri",
    "I love you and that's all I really know. -Liam Neeson",
    "You are the finest, loveliest, tenderest, and most beautiful person I have ever known and even that is an understatement. -F. Scott Fitzgerald",
    "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine. -Maya Angelou",
    "I love you right up to the moon and back. -Sam McBratney",
    "The minute I heard my first love story, I started looking for you, not knowing how blind that was. -Rumi",
    "I love you more than yesterday, less than tomorrow. -Edmond Rostand",
    "I want all of you, forever, you and me, every day. -Nicholas Sparks",
    "You know you're in love when you can't fall asleep because reality is finally better than your dreams. -Dr. Seuss",
    "I love you. I am at rest with you. I have come home. -Dorothy L. Sayers",
    "I love you because the entire universe conspired to help me find you. -Paulo Coelho",
    "To love is nothing. To be loved is something. But to love and be loved, that's everything. -T. Tolis",
    "Whatever happens tomorrow, we've had today. -David Nicholls",
    "I swear I couldn't love you more than I do right now, and yet I know I will tomorrow. -Leo Christopher",
    "You are the last thought in my mind before I drift off to sleep and the first thought when I wake up each morning.",
    "I love you for all that you are, all that you have been, and all you're yet to be.",
    "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible. -Nora Ephron",
    "I love you as the plant that never blooms but carries in itself the light of hidden flowers. -Pablo Neruda",
    "I love you, I love you, I love you. I'll say it a million times if it still doesn't feel like enough. -Lang Leav",
    "I love you for the part of me that you bring out. -Roy Croft",
    "If I know what love is, it is because of you. -Hermann Hesse",
    "You're my end and my beginning, even when I lose I'm winning. -John Legend",
    "I love you every minute of every day.",
    "Love is friendship that has caught fire. -Ann Landers",
    "I need you like a heart needs a beat.",
    "There is a madness in loving you, a lack of reason that makes it feel so flawless. -Leo Christopher",
    "I love you simply, without problems or pride. -Pablo Neruda",
    "I will love you until the stars go out, and the tides no longer turn.",
    "Take my hand, take my whole life too, for I can't help falling in love with you. -Elvis Presley",
    "I love you. Remember. They cannot take it. -Lauren Oliver",
    "I love you. You annoy me more than I ever thought possible, but I love you. -Jenny Han",
    "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. -Lao Tzu",
    "I love you. I knew it the minute I met you. -Oliver Wendell Holmes",
    "I love you more than words can wield the matter. -William Shakespeare",
    "Love is like the wind, you can't see it but you can feel it. -Nicholas Sparks",
    "I've tried so many times to think of a new way to say it, and it's still I love you. -Zelda Fitzgerald",
    "You are my sun, my moon, and all my stars. -E.E. Cummings",
    "I choose you. And I'll choose you over and over and over. Without pause, without a doubt, in a heartbeat. I'll keep choosing you.",
    "My love for you has no depth; its boundaries are ever-expanding. -Christina White",
    "I love thee with the breath, smiles, tears, of all my life. -Elizabeth Barrett Browning",
    "You don't love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear. -Oscar Wilde",
    "And in her smile I see something more beautiful than the stars. -Beth Ravis",
    "If you remember me, then I don't care if everyone else forgets. -Haruki Murakami",
    "I'm much more me when I'm with you.",
    "You are always on my mind. -Willie Nelson",
    "If I did anything right in my life it was when I gave my heart to you.",
    "To the world you may be one person, but to one person you are the world. -Dr. Seuss",
    "Your voice makes me melt.",
    "Love is composed of a single soul inhabiting two bodies. -Aristotle",
    "I love you more than coffee, but please don't make me prove it. -Elizabeth Evans",
    "We loved with a love that was more than love. -Edgar Allan Poe",
    "I still fall for you every day.",
    "For it was not into my ear you whispered, but into my heart. It was not my lips you kissed, but my soul. -Judy Garland",
    "Because of you, I laugh a little harder, cry a little less, and smile a lot more.",
    "You are the source of my joy, the center of my world and the whole of my heart.",
    "At the touch of love everyone becomes a poet. -Plato",
    "If you live to be 100, I hope I live to be 100 minus 1 day, so I never have to live without you. -Winnie the Pooh",
    "In case you ever foolishly forget: I am never not thinking of you. -Virginia Woolf",
    "I'm in love with you, and I know that love is just a shout into the void, and that oblivion is inevitable. -John Green",
    "When I look into your eyes, I know I have found the mirror of my soul. -Joey W. Hill",
    "I will stop loving you when an apple falls from an orange tree, on the 30th of February"
];